services:
 - type: web
    name: classplay
    runtime: static
    buildCommand: yarn build
    staticPublishPath: ./
    previews:
      generation: automatic
    buildFilter:
      paths:
      - /
    headers:
      - path: /
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
