name: Sync with Upstream

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  UPSTREAM_REPO: "useclassplay/useclassplay.github.io"
  BRANCH: "main"

defaults:
  run:
    shell: bash

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git
          git fetch upstream

      - name: Sync with Upstream
        run: |
          git merge upstream/${{ env.BRANCH }} --no-edit || true

      - name: Push Changes to Fork
        run: |
          git push origin ${{ env.BRANCH }}
